function generateModule(type, name) {

    const safeName = String(name || "")
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9_]+/g, "_")
        .replace(/_+/g, "_")
        .replace(/^_|_$/g, "");

    if (!safeName) {
        return { error: "invalid name" };
    }

    const modules = {
        api: {
            file: `${safeName}_api.py`,
            content:
`"""
Flask API Module: ${name}
Auto-generated by Sextant Self Generator
"""

from flask import Flask

app = Flask(__name__)

@app.route("/")
def home():
    return {"status": "online", "module": "${name}"}
`
        },

        service: {
            file: `${safeName}_service.py`,
            content:
`"""
Service Module: ${name}
Auto-generated by Sextant Self Generator
"""

class ${safeName.charAt(0).toUpperCase() + safeName.slice(1)}Service:
    def __init__(self):
        self.name = "${name}"

    def run(self):
        return f"Service running: {self.name}"
`
        },

        model: {
            file: `${safeName}_model.py`,
            content:
`"""
Data Model Module: ${name}
Auto-generated by Sextant Self Generator
"""

class ${safeName.charAt(0).toUpperCase() + safeName.slice(1)}Model:
    def __init__(self, data=None):
        self.data = data or {}

    def serialize(self):
        return self.data
`
        }
    };

    return modules[type] || {
        error: "unknown type",
        allowed: Object.keys(modules)
    };
}
