function generateModule(type, name, options = {}) {

    // =========================
    // 1. SANITIZE INPUT
    // =========================
    const rawName = String(name || "");

    const safeName = rawName
        .trim()
        .toLowerCase()
        .replace(/[^a-z0-9_]+/g, "_")
        .replace(/_+/g, "_")
        .replace(/^_|_$/g, "");

    if (!safeName) {
        return {
            error: "invalid name",
            input: name
        };
    }

    // Convert to PascalCase for class names
    const className = safeName
        .split("_")
        .map(w => w.charAt(0).toUpperCase() + w.slice(1))
        .join("");

    // =========================
    // 2. MODULE REGISTRY
    // =========================
    const registry = {

        api: () => ({
            file: `${safeName}_api.py`,
            content:
`"""
Flask API Module: ${rawName}
Auto-generated by Sextant Self Generator
"""

from flask import Flask, jsonify

app = Flask(__name__)

@app.route("/")
def home():
    return jsonify({
        "status": "online",
        "module": "${rawName}"
    })
`
        }),

        service: () => ({
            file: `${safeName}_service.py`,
            content:
`"""
Service Module: ${rawName}
Auto-generated by Sextant Self Generator
"""

class ${className}Service:
    def __init__(self):
        self.name = "${rawName}"

    def run(self):
        return f"Service running: {self.name}"
`
        }),

        model: () => ({
            file: `${safeName}_model.py`,
            content:
`"""
Data Model Module: ${rawName}
Auto-generated by Sextant Self Generator
"""

class ${className}Model:
    def __init__(self, data=None):
        self.data = data or {}

    def serialize(self):
        return self.data
`
        })
    };

    // =========================
    // 3. VALIDATE TYPE
    // =========================
    if (!registry[type]) {
        return {
            error: "unknown type",
            requested: type,
            allowed: Object.keys(registry)
        };
    }

    // =========================
    // 4. GENERATE MODULE
    // =========================
    const module = registry[type]();

    // =========================
    // 5. OPTIONAL METADATA LAYER
    // =========================
    return {
        meta: {
            type,
            name: rawName,
            safeName,
            className,
            timestamp: new Date().toISOString()
        },
        ...module
    };
}
